# Persistent Volume for PostgreSQL
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  storageClassName: hostpath-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/data/postgres"

---
# Persistent Volume Claim for PostgreSQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath-storage
  resources:
    requests:
      storage: 20Gi
---
# Secret for PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: devops-tools
type: Opaque
stringData:
  POSTGRES_USER: backstage
  POSTGRES_PASSWORD: backstage
  POSTGRES_DB: backstage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
          command: ["/bin/sh", "-c"]
          args:
            - |
              docker-entrypoint.sh postgres &
              sleep 5
              psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'backstage'" | grep -q 1 || psql -U postgres -c "CREATE DATABASE backstage WITH OWNER backstage;"
              wait
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: devops-tools
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: devops-tools
data:
  app-config.yaml: |
    app:
      title: Backstage
    backend:
      database:
        client: pg
        connection: "postgres://backstage:backstage@postgres.devops-tools.svc.cluster.local:5432/backstage"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: ghcr.io/backstage/backstage:latest
          env:
            - name: APP_CONFIG_backend_database_connection
              value: "postgres://backstage:backstage@postgres.devops-tools.svc.cluster.local:5432/backstage"
          ports:
            - containerPort: 7007
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: backstage-config
---
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: devops-tools
spec:
  selector:
    app: backstage
  ports:
    - protocol: TCP
      port: 30091
      targetPort: 7007
  type: NodePort
