kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
  labels:
    ingress-ready: "true" # Required for ingress-nginx scheduling
  kubeadmConfigPatches:
    - |
      kind: ClusterConfiguration
      apiServer:
        extraArgs:
          "admission-control-config-file": "/etc/kubernetes/admission-control.yaml"
  extraPortMappings:
    - containerPort: 80
      hostPort: 80
    - containerPort: 443
      hostPort: 443

- role: worker
  extraMounts:
    - hostPath: /home/appdata
      containerPath: /home/data
