kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
  extraPortMappings:
  # Web Apps & DevOps Tools
  - containerPort: 80
    hostPort: 80
  - containerPort: 443
    hostPort: 443
  - containerPort: 8080
    hostPort: 8080
  - containerPort: 9000
    hostPort: 9000  # SonarQube
  - containerPort: 5000
    hostPort: 5000  # Docker Registry

  # Monitoring & Logging
  - containerPort: 3000
    hostPort: 3000  # Grafana
  - containerPort: 9090
    hostPort: 9090  # Prometheus
  - containerPort: 5601
    hostPort: 5601  # Kibana
  - containerPort: 9200
    hostPort: 9200  # Elasticsearch

  # Database Services
  - containerPort: 5432
    hostPort: 5432  # PostgreSQL
  - containerPort: 3306
    hostPort: 3306  # MySQL
  - containerPort: 27017
    hostPort: 27017 # MongoDB

  # Kubernetes & NodePort Support
  - containerPort: 6443
    hostPort: 6443  # Kubernetes API
  - containerPort: 10250
    hostPort: 10250 # Kubelet API

- role: worker
  extraMounts:
  - hostPath: C:\\appdata
    containerPath: /home/appdata


# kind create cluster --config kind-cluster-config-windows.yaml --name kind
# kubectl apply -f namespace.yaml
# kubectl config set-context --current --namespace=devops-tools