kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha7
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        enable-admission-plugins: "NodeRestriction,AlwaysPullImages"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
  - containerPort: 443
    hostPort: 443
- role: worker
  extraMounts:
  - hostPath: /home/data
    containerPath: /home/data
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "worker-node=true"
  # Improves network performance with kube-proxy config
networking:
  kubeProxyMode: "iptables"
  podSubnet: "10.244.0.0/16"  # Define pod subnet explicitly



# kind create cluster --config kind-cluster-config.yaml --name kind
# kubectl apply -f namespace.yaml
# kubectl config set-context --current --namespace=devops-tools
