kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 1-65535
    hostPort: 1-65535
    protocol: TCP

- role: worker
  extraMounts:
  - hostPath: C:\\appdata
    containerPath: /home/appdata


# kind create cluster --config kind-cluster-config.yaml --name kind
# kubectl apply -f namespace.yaml
# kubectl config set-context --current --namespace=devops-tools