kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  extraMounts:
    - hostPath: /home/appdata
      containerPath: /home/data

- role: worker
  extraMounts:
    - hostPath: /home/appdata
      containerPath: /home/data


# kind create cluster --config kind-cluster-config.yaml --name kind
# kubectl apply -f namespace.yaml
# kubectl config set-context --current --namespace=devops-tools