kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
  labels:
    ingress-ready: "true" # Required for ingress-nginx scheduling
  kubeadmConfigPatches:
    - |
      kind: ClusterConfiguration
      apiServer:
        extraArgs:
          "enable-admission-plugins": "PodSecurityPolicy"
  extraPortMappings:
    - containerPort: 80
      hostPort: 80

- role: worker
  extraMounts:
    - hostPath: /home/appdata
      containerPath: /home/data


# kind create cluster --config kind-cluster-config.yaml --name kind
# kubectl apply -f namespace.yaml
# kubectl config set-context --current --namespace=devops-tools