kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31000
    hostPort: 80 #gitlab port

  - containerPort: 31001
    hostPort: 8080 #jenkins port

  - containerPort: 31002
    hostPort: 5432 #postgres port

  - containerPort: 31003
    hostPort: 5433 #postgres port

  - containerPort: 31004
    hostPort: 9099 #prometheus port

  - containerPort: 31005
    hostPort: 6000 #wiki port

  - containerPort: 31006
    hostPort: 3000 #grafana port

  - containerPort: 31007
    hostPort: 9000 #openproject port

  - containerPort: 31008
    hostPort: 8090 #zap port

- role: worker
  extraMounts:
  - hostPath: C:\\appdata
    containerPath: /home/appdata


# kind create cluster --config kind-cluster-config-windows.yaml --name kind
# kubectl apply -f namespace.yaml
# kubectl config set-context --current --namespace=devops-tools