kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
  labels:
    ingress-ready: "true"
  kubeadmConfigPatches:
    - |
      kind: ClusterConfiguration
      apiServer:
        extraArgs:
          "admission-control-config-file": "/etc/kubernetes/admission-control.yaml"
  extraMounts:
    - hostPath: /home/user/admission-control.yaml
      containerPath: /etc/kubernetes/admission-control.yaml

- role: worker
  extraMounts:
    - hostPath: /home/appdata
      containerPath: /home/data
