kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31000
    hostPort: 80 #gitlab port

  - containerPort: 31001
    hostPort: 8080 #jenkins port

  - containerPort: 31002
    hostPort: 5432 #postgres port

  - containerPort: 31003
    hostPort: 5433 #postgres port

  - containerPort: 31004
    hostPort: 9099 #prometheus port

  - containerPort: 31005
    hostPort: 6000 #wiki port

  - containerPort: 31006
    hostPort: 3000 #grafana port

  - containerPort: 31007
    hostPort: 9000 #openproject port

  - containerPort: 31008
    hostPort: 8090 #zap port

- role: worker
  extraMounts:
  - hostPath: /home/appdata/gitlab
    containerPath: /home/data/gitlab

  - hostPath: /home/appdata/jenkins
    containerPath: /home/data/jenkins

  - hostPath: /home/appdata/postgres
    containerPath: /home/data/postgres

  - hostPath: /home/appdata/grafana
    containerPath: /home/data/grafana

  - hostPath: /home/appdata/prometheus
    containerPath: /home/data/prometheus

  - hostPath: /home/appdata/wiki
    containerPath: /home/data/wiki

  - hostPath: /home/appdata/openproject
    containerPath: /home/data/openproject

  - hostPath: /home/appdata/zap
    containerPath: /home/data/zap

  - hostPath: /home/appdata/workspace
    containerPath: /home/data/workspace
    
  - hostPath: /home/appdata/other
    containerPath: /home/data/other

# kind create cluster --config kind-cluster-config.yaml --name kind
# kubectl apply -f namespace.yaml
# kubectl config set-context --current --namespace=devops-tools
