kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 30080
      hostPort: 30080
      protocol: TCP
    - containerPort: 30081
      hostPort: 30081 #Jenkins
      protocol: TCP
    - containerPort: 30082
      hostPort: 30082
      protocol: TCP
    - containerPort: 30083
      hostPort: 30083
      protocol: TCP
    - containerPort: 30084
      hostPort: 30084
      protocol: TCP
    - containerPort: 30085
      hostPort: 30085
      protocol: TCP
    - containerPort: 30086
      hostPort: 30086
      protocol: TCP
    - containerPort: 30087
      hostPort: 30087
      protocol: TCP
    - containerPort: 30088
      hostPort: 30088
      protocol: TCP
    - containerPort: 30089
      hostPort: 30089
      protocol: TCP
    - containerPort: 30090
      hostPort: 30090
      protocol: TCP
    - containerPort: 30091
      hostPort: 30091
      protocol: TCP
    - containerPort: 30092
      hostPort: 30092
      protocol: TCP
    - containerPort: 30093
      hostPort: 30093
      protocol: TCP
    - containerPort: 30094
      hostPort: 30094
      protocol: TCP
    - containerPort: 30095
      hostPort: 30095
      protocol: TCP
    - containerPort: 30096
      hostPort: 30096
      protocol: TCP
    - containerPort: 30097
      hostPort: 30097
      protocol: TCP
    - containerPort: 30098
      hostPort: 30098
      protocol: TCP
    - containerPort: 30099
      hostPort: 30099
      protocol: TCP

- role: worker
  extraMounts:
  - hostPath: /home/data
    containerPath: /home/data


# kind create cluster --config kind-cluster-config.yaml --name kind
# kubectl apply -f namespace.yaml
# kubectl config set-context --current --namespace=devops-tools
