# kubectl create secret generic postgres-secret --namespace=devops-tools --from-literal=POSTGRES_DB=wikijs --from-literal=POSTGRES_USER=wikiuser --from-literal=POSTGRES_PASSWORD=wikisecret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-postgres
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki-postgres
  template:
    metadata:
      labels:
        app: wiki-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: wiki-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: wiki-postgres-service
  namespace: devops-tools
spec:
  selector:
    app: wiki-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      containers:
        - name: wiki
          image: requarks/wiki:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_TYPE
              value: "postgres"
            - name: DB_HOST
              value: "wiki-postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: wiki-storage
              mountPath: /wiki/data
      volumes:
        - name: wiki-storage
          persistentVolumeClaim:
            claimName: wiki-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: wiki-service
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app: wiki
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32006

#Volumes
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage-wiki
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

#Persistent Volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-pv
  labels:
    type: local
spec:
  storageClassName: local-storage-wiki
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-worker

#Persistent Volume Claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiki-pvc
  namespace: devops-tools
spec:
  storageClassName: local-storage-wiki
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
