---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki
  namespace: devops-tools
  spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      nodeSelector:
        kubernetes.io/hostname: kind-worker
      containers:
        - name: wiki
          image: requarks/wiki:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_TYPE
              value: "postgres"
            - name: DB_HOST
              value: "postgres.devops-tools.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                  secretKeyRef:
                    name: postgres-secrets
                    key: POSTGRES_USER
            - name: DB_PASS
              valueFrom:
                  secretKeyRef:
                    name: postgres-secrets
                    key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                  secretKeyRef:
                    name: postgres-secrets
                    key: POSTGRES_DB
          volumeMounts:
            - name: wiki-storage
              mountPath: /wiki/data
      volumes:
        - name: wiki-storage
          persistentVolumeClaim:
            claimName: wiki-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: wiki-service
  spec:
  type: ClusterIP
  selector:
    app: wiki
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 3000
      nodePort: 32005
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-wiki-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
# Persistent Volumes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-pv
  labels:
    app: wiki
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-wiki-storage
  hostPath:
    path: /home/data/wiki
---
# Persistent Volume Claims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiki-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-wiki-storage
  resources:
    requests:
      storage: 5Gi
