---
# Storage Class (for Kind)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hostpath-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate

---
# Persistent Volume for Wiki.js
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-pv
spec:
  storageClassName: hostpath-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/data/wiki"

---
# Persistent Volume Claim for Wiki.js
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiki-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath-storage
  resources:
    requests:
      storage: 1Gi

---
# ConfigMap for Wiki.js Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: wiki-config
  namespace: devops-tools
data:
  config.yml: |
    port: ${PORT}
    bindIP: 0.0.0.0
    db:
      type: ${DB_TYPE}
      host: ${DB_HOST}
      port: ${DB_PORT}
      user: ${DB_USER}
      pass: ${DB_PASS}
      db: ${DB_NAME}
      storage: ${DB_FILEPATH}
      ssl: ${DB_SSL}
    ssl:
      enabled: ${SSL_ACTIVE}
      port: 3443
      provider: letsencrypt
      domain: ${LETSENCRYPT_DOMAIN}
      subscriberEmail: ${LETSENCRYPT_EMAIL}
    logLevel: ${LOG_LEVEL:info}
    logFormat: ${LOG_FORMAT:default}
    ha: ${HA_ACTIVE}

---
# Deployment for Wiki.js
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      containers:
        - name: wiki
          image: requarks/wiki:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: DB_TYPE
              value: "postgres"
            - name: DB_HOST
              value: "postgres.devops-tools.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_DB
          volumeMounts:
            - name: wiki-storage
              mountPath: /var/wiki
            - name: config-volume
              mountPath: /wiki/config.yml
              subPath: config.yml
      volumes:
        - name: wiki-storage
          persistentVolumeClaim:
            claimName: wiki-pvc
        - name: config-volume
          configMap:
            name: wiki-config

---
# Service for Wiki.js
apiVersion: v1
kind: Service
metadata:
  name: wiki-service
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app: wiki
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 3001
      nodePort: 31005
