apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/wiki"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiki-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki-postgres
  template:
    metadata:
      labels:
        app: wiki-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: "wikijs"
            - name: POSTGRES_USER
              value: "wikiuser"
            - name: POSTGRES_PASSWORD
              value: "wikisecret"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: wiki-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: wiki-postgres-service
spec:
  selector:
    app: wiki-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      containers:
        - name: wiki
          image: requarks/wiki:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_TYPE
              value: "postgres"
            - name: DB_HOST
              value: "wiki-postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "wikiuser"
            - name: DB_PASS
              value: "wikisecret"
            - name: DB_NAME
              value: "wikijs"
          volumeMounts:
            - name: wiki-storage
              mountPath: /wiki/data
      volumes:
        - name: wiki-storage
          persistentVolumeClaim:
            claimName: wiki-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: wiki-service
spec:
  type: NodePort
  selector:
    app: wiki
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32080  # Change this if needed
