#Deployment Grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops-tools
  labels:
    app: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-data
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-pvc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 1

#Service Grafana
---
apiVersion: v1
kind: Service
metadata:
  namespace: devops-tools
  name: grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
      nodePort: 30084
  selector:
    app: grafana

#Persistent Volume and Persistent Volume Claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: devops-tools
  name: grafana-pv
spec:
  storageClassName: hostpath-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/data/grafana"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: devops-tools
  name: grafana-pvc
spec:
  storageClassName: hostpath-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi