global:
  edition: ee  # Use "ee" for GitLab Enterprise Edition, "ce" for Community Edition

  ## GitLab Initial Configuration
  hosts:
    domain: "devops.local"
    gitlab:
      name: "devops.local"

  ## Enable PostgreSQL
  psql:
    enabled: true
  postgresql:
    install: true
    postgresqlUsername: gitlab
    postgresqlDatabase: gitlabhq_production
    persistence:
      enabled: true
      size: 10Gi
      storageClass: ""
      hostPath: "/home/appdata/gitlab/postgresql"

  ## Enable Redis
  redis:
    enabled: true
    persistence:
      enabled: true
      size: 5Gi
      storageClass: ""
      hostPath: "/home/appdata/gitlab/redis"

  ## Disable Object Storage (MinIO)
  minio:
    enabled: false
  objectStorage:
    enabled: false
  artifacts:
    enabled: false
    objectStore:
      enabled: false
  lfs:
    enabled: false
    objectStore:
      enabled: false
  uploads:
    enabled: false
    objectStore:
      enabled: false
  packages:
    enabled: false
    objectStore:
      enabled: false

  ## Disable Global Certificates
  certificates:
    enabled: false

  ## Disable CertManager
  certmanager:
    install: false

  ## Ensure Object Storage is Completely Disabled
  appConfig:
    object_store:
      enabled: false

  ## Toolbox Backup Configuration
  toolbox:
    backups:
      objectStorage:
        config:
          secret: ""

## Disable CertManager Issuer
certmanager-issuer:
  enabled: false
  email: "disabled@example.com"

## Disable Ingress, Use NodePort Instead
ingress:
  enabled: false

## Expose GitLab Services via NodePort
gitlab:
  webservice:
    service:
      type: NodePort
      nodePort: 31000  # HTTP

## Enable GitLab Runner
gitlab-runner:
  enabled: true
  runners:
    privileged: true
    executor: "kubernetes"
    namespace: "gitlab-runner"
  service:
    type: NodePort
    nodePort: 32000  # Runner Service NodePort

## Backup Configuration
backup:
  enabled: false