apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab
  namespace: devops-tools
spec:
  serviceName: "gitlab"
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /var/opt/gitlab
            - name: config
              mountPath: /etc/gitlab
          env:
            - name: EXTERNAL_URL
              value: "http://devops.local/"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 20
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteMany"]
        storageClassName: local-path
        resources:
          requests:
            storage: 20Gi
        volumeName: local-var
    - metadata:
        name: config
      spec:
        accessModes: ["ReadWriteMany"]
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
        volumeName: local-etc

---
# GitLab Service
apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
    - protocol: TCP
      nodePort: 31000
      port: 8081
      targetPort: 80

---
# Persistent Volumes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-var
  namespace: devops-tools
  labels:
    app: gitlab
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /home/data/gitlab/var
  claimRef:
    name: data-gitlab-0
    namespace: devops-tools
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-etc
  namespace: devops-tools
  labels:
    app: gitlab
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /home/data/gitlab/etc
  claimRef:
    name: config-gitlab-0
    namespace: devops-tools

---
# Persistent Volume Claims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-var
  namespace: devops-tools
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-etc
  namespace: devops-tools
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
