apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ee:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /var/opt/gitlab
            - name: config
              mountPath: /etc/gitlab
          env:
            - name: EXTERNAL_URL
              value: "http://devops.local:30086"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 20
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: local-var
        - name: config
          persistentVolumeClaim:
            claimName: local-etc

---
# GitLab Service
apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
    - protocol: TCP
      nodePort: 30086
      port: 80
      targetPort: 80

---
# Persistent Volumes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-var
  namespace: devops-tools
  labels:
    app: gitlab
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /home/data/gitlab/var
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-etc
  namespace: devops-tools
  labels:
    app: gitlab
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /home/data/gitlab/etc

---
# Persistent Volume Claims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-var
  namespace: devops-tools
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-etc
  namespace: devops-tools
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi