
#Deploying Gitlab on Kubernetes
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gitlab-deployment
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      name: gitlab-dep-pod
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /var/opt/gitlab
            name: data
          - mountPath: /etc/gitlab
            name: config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: local-var
        - name: config
          persistentVolumeClaim:
            claimName: local-etc
          
#Service
---
kind: Service
apiVersion: v1
metadata:
  name: gitlab-service
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
    - protocol: TCP
      nodePort: 31000
      port: 80

#Persistent Volume and Persistent Volume Claim
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-var
  namespace: devops-tools
  labels:
    app: gitlab
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /home/data/gitlab/var
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-etc
  namespace: devops-tools
  labels:
    app: gitlab
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /home/data/gitlab/etc

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-var
  namespace: devops-tools
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-etc
  namespace: devops-tools
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi