apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner
  namespace: devops-tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-runner-role
  namespace: devops-tools
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "services"]
    verbs: ["get", "list", "create", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-runner-rolebinding
  namespace: devops-tools
subjects:
  - kind: ServiceAccount
    name: gitlab-runner
    namespace: devops-tools
roleRef:
  kind: Role
  name: gitlab-runner-role
  apiGroup: rbac.authorization.k8s.io
