runners:
  config: |
    [[runners]]
      executor = "kubernetes"
      [runners.kubernetes]
        image = "alpine"
        privileged = true
        pull_policy = "if-not-present"
        [runners.kubernetes.node_selector]
          "cloud.google.com/gke-nodepool" = "default-pool"
        [runners.kubernetes.affinity]
          podAntiAffinity = { requiredDuringSchedulingIgnoredDuringExecution = [] }
    [[runners.kubernetes.volumes.empty_dir]]
      name = "docker-certs"
      mount_path = "/certs/client"
      medium = "Memory"
