apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  labels:
    app: backstage
type: Opaque
data:
  GITHUB_CLIENT_ID: <base64_encoded_client_id>
  GITHUB_CLIENT_SECRET: <base64_encoded_client_secret>
  GITHUB_TOKEN: <base64_encoded_github_pat>
  POSTGRES_USER: <base64_encoded_postgres_user>
  POSTGRES_PASSWORD: <base64_encoded_postgres_password>
  POSTGRES_DB: <base64_encoded_postgres_db>
