apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-backstage
  namespace: devops-tools
  labels:
    app: nginx-backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-backstage
  template:
    metadata:
      labels:
        app: nginx-backstage
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-backstage
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app: nginx-backstage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: devops-tools
data:
  default.conf: |
    server {
        listen 80;

        server_name localhost;

        location / {
            proxy_pass http://backstage.devops-tools.svc.cluster.local:7007;  # Internal service
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
