# install ingress controller kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: devsecops-apps.com
    http:
      paths:
      - path: /gitlab
        pathType: Prefix
        backend:
          service:
            name: gitlab-service  # Just the service name
            port:
              number: 80
      - path: /jenkins
        pathType: Prefix
        backend:
          service:
            name: jenkins-service  # Just the service name
            port:
              number: 80
