apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-db
  namespace: devops-tools
data:
  init-db.sql: |
    DO $$ 
    BEGIN 
      IF NOT EXISTS (SELECT FROM pg_database WHERE datname = 'wikijs') THEN 
        CREATE DATABASE wikijs; 
      END IF; 
    END $$;
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: devops-tools
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          command: ["/bin/sh", "-c"]
          args:
            - >
              until psql -U postgres -c "SELECT 1" > /dev/null 2>&1; do sleep 1; done;
              psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'wikijs'" | grep -q 1 || psql -U postgres -c "CREATE DATABASE wikijs";
              exec docker-entrypoint.sh postgres;
          envFrom:
            - secretRef:
                name: postgres-secrets
          ports:
            - containerPort: 5432
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U postgres -h 127.0.0.1 -p 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U postgres -h 127.0.0.1 -p 5432
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 1
              memory: 2Gi
            limits:
              cpu: 2
              memory: 4Gi
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data-disk
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: data-disk
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-script
          configMap:
            name: postgres-init-db
      nodeSelector:
        kubernetes.io/hostname: kind-worker
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: devops-tools
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-postgres
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    type: local
    app: postgres
spec:
  storageClassName: local-postgres
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/data/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kind-worker
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-postgres
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: devops-tools
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: wikijs