apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-db
  namespace: devops-tools
data:
  init-db.sql: |
    CREATE DATABASE IF NOT EXISTS wikijs;
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-wikijs
  namespace: devops-tools
spec:
  serviceName: postgres-wikijs
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          envFrom:
            - secretRef:
                name: postgres-secrets
          ports:
            - containerPort: 5432
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U postgres -h 127.0.0.1 -p 5432
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U postgres -h 127.0.0.1 -p 5432
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 1
              memory: 2Gi
            limits:
              cpu: 2
              memory: 4Gi
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data-disk
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: data-disk
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-script
          configMap:
            name: postgres-init-db
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-wikijs
  namespace: devops-tools
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-postgres # Replace with cloud-provided StorageClass for production
provisioner: kubernetes.io/no-provisioner # Replace for production
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    type: local
    app: postgres
spec:
  storageClassName: local-postgres # Match StorageClass name
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce # Consider ReadWriteMany if your storage supports it
  local:
    path: /home/data/postgres # Adjust path if not using local volume
  nodeAffinity: # Remove for production unless absolutely necessary
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kind-worker # Remove for production
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-postgres # Match StorageClass name
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: devops-tools
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres # **IMPORTANT: CHANGE THIS PASSWORD!**
  POSTGRES_DB: wikijs