apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: devops-tools
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 999
      initContainers:
        - name: init-db
          image: postgres:15
          envFrom:
            - secretRef:
                name: postgres-secrets
          command:
            - /bin/sh
            - -c
            - |
              until pg_isready -h postgres -p 5432 -U postgres; do
                echo "Waiting for PostgreSQL...";
                sleep 5;
              done
              psql -U postgres -d template1 -c "CREATE DATABASE gitleak;" || echo "Error creating gitleak"
              psql -U postgres -d template1 -c "CREATE DATABASE owaspdependency;" || echo "Error creating owaspdependency"
              psql -U postgres -d template1 -c "CREATE DATABASE zap;" || echo "Error creating zap"
              psql -U postgres -d template1 -c "CREATE DATABASE trivy;" || echo "Error creating trivy"
              psql -U postgres -d template1 -c "CREATE DATABASE semgrep;" || echo "Error creating semgrep"
      containers:
        - name: postgres
          image: postgres:15
          envFrom:
            - secretRef:
                name: postgres-secrets
          ports:
            - containerPort: 5432
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 1
              memory: 2Gi
            limits:
              cpu: 2
              memory: 4Gi
          securityContext:
            runAsUser: 999
          volumeMounts:
            - name: data-disk
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-disk
          persistentVolumeClaim:
            claimName: postgres-pvc
      nodeSelector:
        kubernetes.io/hostname: kind-worker
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: devops-tools
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-postgres
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    type: local
    app: postgres
spec:
  storageClassName: local-postgres
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/data/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kind-worker
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: devops-tools
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-postgres
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: devops-tools
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"