apiVersion: apps/v1
kind: Deployment
metadata:
  name: zap
  namespace: devops-tools
  labels:
    app: zap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zap
  template:
    metadata:
      labels:
        app: zap
    spec:
      initContainers:
        - name: init-permissions
          image: busybox
          command:
            - "sh"
            - "-c"
            - >
              mkdir -p /zap/reports && 
              chown -R 1000:1000 /zap/reports && 
              chmod -R 775 /zap/reports
          volumeMounts:
            - name: zap-reports
              mountPath: /zap/reports
      containers:
        - name: zap
          image: zaproxy/zap-stable
          workingDir: /zap/reports
          args:
            - "zap.sh"
            - "-daemon"
            - "-host"
            - "0.0.0.0"
            - "-port"
            - "8090"
            - "-config"
            - "api.disablekey=true"
            - "-config"
            - "api.addrs.addr.name=.*"
            - "-config"
            - "api.addrs.addr.regex=true"
            - "-addonupdate"
            - "-addoninstall"
            - "reports"
            - "-addoninstall"
            - "reportTemplates"
            - "-Xmx8192m"
            - "-config"
            - "scanner.threadPerHost=5"
            - "-config"
            - "selenium.firefox.webdriver=http://selenium-firefox.devops-tools.svc.cluster.local:4444/wd/hub"
            - "-config"
            - "selenium.headless=true"
            - "-config"
            - "spider.threads=2"
            - "-config"
            - "ascan.threads=2"
          env:
            - name: ZAP_JAVA_OPTS
              value: "-config selenium.firefox.webdriver=http://selenium-firefox.devops-tools.svc.cluster.local:4444/wd/hub"
          ports:
            - containerPort: 8090
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          livenessProbe:
            httpGet:
              path: /JSON/core/view/version/
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /JSON/core/view/version/
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 10
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - >
                    until curl -s http://selenium-firefox:4444/status | grep -q '"ready": true'; do sleep 5; done &&
                    chown -R 1000:1000 /zap/reports && 
                    chmod -R 775 /zap/reports && 
                    curl -s http://localhost:8090/JSON/autoupdate/action/installAddon/?id=reports && 
                    curl -s http://localhost:8090/JSON/autoupdate/action/installAddon/?id=reportTemplates
          volumeMounts:
            - name: zap-reports
              mountPath: /zap/reports
      volumes:
        - name: zap-reports
          hostPath:
            path: /home/data/zap-reports
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: zap
  namespace: devops-tools
  labels:
    app: zap
spec:
  type: NodePort
  selector:
    app: zap
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-firefox
  namespace: devops-tools
  labels:
    app: selenium-firefox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-firefox
  template:
    metadata:
      labels:
        app: selenium-firefox
    spec:
      containers:
        - name: selenium-firefox
          image: selenium/standalone-firefox:latest
          ports:
            - containerPort: 4444
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-firefox
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app: selenium-firefox
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444
      nodePort: 30444