apiVersion: apps/v1
kind: Deployment
metadata:
  name: zap
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zap
  template:
    metadata:
      labels:
        app: zap
    spec:
      containers:
        - name: zap
          image: zaproxy/zap-stable
          ports:
            - containerPort: 8080
          env:
            - name: ZAP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: zap-api-key
                  key: api_key
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx2g -XX:MaxPermSize=512m -XX:+UseG1GC"
          command:
            - zap.sh
          args:
            - "-daemon"
            - "-host"
            - "0.0.0.0"
            - "-port"
            - "8080"
            - "-config"
            - "connection.requestTimeoutInMs=60000"
            - "-config"
            - "api.addrs.addr.name=.*"  # Allow all IPs
            - "-config"
            - "api.addrs.addr.regex=true"
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: zap-service
  namespace: devops-tools
spec:
  selector:
    app: zap
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 8080