apiVersion: apps/v1
kind: Deployment
metadata:
  name: zap
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zap
  template:
    metadata:
      labels:
        app: zap
    spec:
      containers:
        - name: zap
          image: zaproxy/zap-stable
          ports:
            - containerPort: 8080  # ZAP's internal port (important: keep this as 8080)
          env:
            - name: ZAP_API_KEY
              value: "-5IrWmmH4xuGCAYjRI1CwOSoxNAHK1ErXfZ4KJ9vMv4"  # Replace with your actual API key
          command:
            - zap.sh
          args:
            - "-daemon"
            - "-host"
            - "0.0.0.0"
            - "-port"
            - "8080" # ZAP's internal port. Must match containerPort
            - "-config"
            - "connection.requestTimeoutInMs=60000"

---
apiVersion: v1
kind: Service
metadata:
  name: zap-service
  namespace: devops-tools
spec:
  type: NodePort  # Important: Use NodePort for external access
  selector:
    app: zap
  ports:
    - protocol: TCP
      port: 9090  # The port you'll access from outside the cluster
      targetPort: 8080  # ZAP's internal port (matches containerPort)
      nodePort: 31003  # Choose an available port on your nodes (30000-32767 range)