apiVersion: apps/v1
kind: Deployment
metadata:
  name: zap
  namespace: devops-tools
  labels:
    app: zap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zap
  template:
    metadata:
      labels:
        app: zap
    spec:
      containers:
        - name: zap
          image: zaproxy/zap-stable
          args: ["zap.sh", "-daemon", "-host", "0.0.0.0", "-port", "8090", "-config", "api.disablekey=true"]
          ports:
            - containerPort: 8090
          resources:
            requests:
              cpu: "2"
              memory: "2Gi"
            limits:
              cpu: "4"
              memory: "4Gi"
          livenessProbe:
            httpGet:
              path: /
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: zap
  namespace: devops-tools
  labels:
    app: zap
spec:
  selector:
    app: zap
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  clusterIP: None  # Headless Service
