apiVersion: apps/v1
kind: Deployment
metadata:
  name: zap
  namespace: zap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zap
  template:
    metadata:
      labels:
        app: zap
    spec:
      containers:
        - name: zap
          image: owasp/zap2docker-stable
          ports:
            - containerPort: 8080  # Default port ZAP runs on
          env:
            - name: ZAP_API_KEY
              value: "your_api_key"  # Set an API key if required
          args:
            - "-daemon"  # Run ZAP in daemon mode (headless)
            - "-host"
            - "0.0.0.0"
            - "-port"
            - "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: zap-service
  namespace: zap
spec:
  selector:
    app: zap
  ports:
    - protocol: TCP
      port: 8080  # The port to expose ZAP on
      targetPort: 8080  # The container port
  type: LoadBalancer  # Optionally, you can use ClusterIP or NodePort based on your use case
