# ZAP Deployment and service
# Service URL = http://zap-service.devops-tools.svc.cluster.local:9090

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zap
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zap
  template:
    metadata:
      labels:
        app: zap
    spec:
      containers:
        - name: zap
          image: zaproxy/zap-stable
          ports:
            - containerPort: 8080
          env:
            - name: ZAP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: zap-api-key
                  key: api_key
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx2g -XX:MaxPermSize=512m -XX:+UseG1GC"
          command:
            - zap.sh
          args:
            - "-daemon"
            - "-host"
            - "0.0.0.0"
            - "-port"
            - "8080"
            - "-config"
            - "connection.requestTimeoutInMs=60000"
      resources:
        requests:
          cpu: "2"  # Increase CPU request
          memory: "4Gi" # Increase memory request
        limits:
          cpu: "4"  # Increase CPU limit
          memory: "8Gi" # Increase memory limit


---
apiVersion: v1
kind: Service
metadata:
  name: zap-service
  namespace: devops-tools
spec:
  type: NodePort  # Important: Use NodePort for external access
  selector:
    app: zap
  ports:
    - protocol: TCP
      port: 9090  # The port you'll access from outside the cluster
      targetPort: 8080  # ZAP's internal port (matches containerPort)
      nodePort: 31003  # Choose an available port on your nodes (30000-32767 range)